apiVersion: v2
type: application
name: vault
version: 0.0.0
appVersion: 1.14.1
description: A tool for secrets management, encryption as a service, and privileged access management
icon: https://www.vaultproject.io/assets/images/mega-nav/logo-vault-0f83e3d2.svg
keywords:
  - vault
  - hashicorp
home: https://www.vaultproject.io/
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/bank-vaults/vault-helm-chart
maintainers:
  - name: Bank Vaults Maintainers
    email: team@bank-vaults.dev
